# Generated by Django 4.2.5 on 2023-10-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_answer_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assert1',
            field=models.CharField(blank=True, default='входные данные : выходные данные', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='assert2',
            field=models.CharField(blank=True, default='входные данные : выходные данные', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='assert3',
            field=models.CharField(blank=True, default='входные данные : выходные данные', max_length=300, null=True),
        ),
    ]
