# Generated by Django 4.2.5 on 2023-11-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_assert1_remove_task_assert2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='test',
        ),
    ]
