# Generated by Django 5.0 on 2023-12-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_profile_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='stat',
            field=models.CharField(choices=[('Решего', 'Решено'), ('Неверное решение', 'Неверное решение'), ('На проверке', 'На проверке')], default='Нет статуса', max_length=60),
        ),
    ]
