# Generated by Django 5.0.1 on 2024-02-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_answer_code_alter_answer_stat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='input_data',
            field=models.CharField(default='Введите входные данные', max_length=100, verbose_name='Входные данные'),
        ),
        migrations.AddField(
            model_name='task',
            name='output_data',
            field=models.CharField(default='Введите выходные данные', max_length=100, verbose_name='Выходные данные'),
        ),
    ]
