# Generated by Django 5.0.1 on 2024-02-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_profile_schedule_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='input_data',
            field=models.TextField(default='Введите входные данные', max_length=200, verbose_name='Входные данные'),
        ),
        migrations.AlterField(
            model_name='task',
            name='output_data',
            field=models.TextField(default='Введите выходные данные', max_length=200, verbose_name='Выходные данные'),
        ),
    ]
