# Generated by Django 5.0.1 on 2024-02-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_task_input_data_alter_task_output_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='solved_problems',
            field=models.IntegerField(default=0, max_length=100, verbose_name='Решенные задачи'),
        ),
    ]
