# Generated by Django 5.0.1 on 2024-05-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_profile_solved_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='solved_problems',
            field=models.IntegerField(default=0, verbose_name='Решенные задачи'),
        ),
    ]
